name: sicopa
description: Sistema de Control Patrimonial (SICOPA) del Estado de MÃ©xico.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.3
  firebase_auth: ^4.7.0
  cloud_functions: ^4.3.3
  mobile_scanner: ^3.2.0
  nfc_manager: ^3.3.0
  file_picker: ^5.3.2
  csv: ^5.0.2
  pdf: ^3.10.3
  printing: ^5.11.0
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
